import type { Metadata } from 'next'

import { MobileHeader } from '@/widgets/MobileHeader'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function MobileLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <MobileHeader />
      <div className="pt-14 h-screen">
        <main>{children}</main>
      </div>
    </>
  )
}
