import type { Metadata } from 'next'
import localFont from 'next/font/local'
import '@/app/styles/globals.css'
import MSWComponent from '@/app/providers/msw-component'
import ReactQueryProviders from '@/app/providers/query-client-provider'
import { SkeletonTheme } from 'react-loading-skeleton'

const pretendard = localFont({
  src: '../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children,
  modal
}: Readonly<{
  children: React.ReactNode
  modal: React.ReactNode
}>) {
  return (
    <html lang="en">
      <MSWComponent />
      <body className={`${pretendard.variable} font-pretendard`}>
        <ReactQueryProviders>
          <SkeletonTheme baseColor="#202124" highlightColor="#38393D">
            {children}
            {modal}
          </SkeletonTheme>
        </ReactQueryProviders>
      </body>
    </html>
  )
}
