import type { Metadata } from 'next'
import localFont from 'next/font/local'
import '@/app/styles/globals.css'
import MSWComponent from '@/app/providers/msw-component'
import ReactQueryProviders from '@/app/providers/query-client-provider'

const pretendard = localFont({
  src: '../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <MSWComponent />
      <body className={`${pretendard.variable} font-pretendard`}>
        <ReactQueryProviders>
          <header
            style={{
              height: '56px',
              position: 'fixed',
              top: 0,
              inset: 0,
              zIndex: '9999',
              backgroundColor: 'beige'
            }}
          >
            header
          </header>
          <main
            style={{
              paddingTop: '56px',
              height: '100vh'
            }}
          >
            {children}
          </main>
        </ReactQueryProviders>
      </body>
    </html>
  )
}
