import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/app/styles/globals.css'
import MSWComponent from '@/app/providers/msw-component'
import ReactQueryProviders from '@/app/providers/query-client-provider'
import { Sidebar } from '@/widgets'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <MSWComponent />
      <body className={inter.className}>
        <ReactQueryProviders>
          <header>header</header>
          <div className="flex">
            <Sidebar />
            <div className="p-12 flex-1">{children}</div>
          </div>
        </ReactQueryProviders>
      </body>
    </html>
  )
}
