import type { Metadata } from 'next'
import { Sidebar } from '@/widgets'
import { Header } from '@/widgets/Header'
import { Suspense } from 'react'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function ExploreLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <Header />
      <div className="flex pt-14 h-screen">
        <Sidebar />
        <main className="p-12 ml-[280px] flex-1">
          <Suspense>{children}</Suspense>
        </main>
      </div>
    </>
  )
}
