import type { Metadata } from 'next'
import { Sidebar } from '@/widgets'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function MainLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div className="flex">
      <Sidebar />
      <div className="p-12 flex-1">{children}</div>
    </div>
  )
}
