import { Header } from '@/widgets/Header'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function DetailPageLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <Header />
      <main className="pt-16 pr-5 pb-5 h-screen">{children}</main>
    </>
  )
}
