import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function DetailPageLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return <div className="px-5 pb-5 h-full overflow-hidden">{children}</div>
}
